log:
  level: debug
  target: stdout|fileout
  sync: true
tcp:
  port: 80
  ip: 10.0.24.17
threadpool:
  min_thread_num: 4
  max_thread_num: 8
mysql:
  user: mysql
  password: eular123
  database: userdb
html:
  root: /home/hsz/VScode/www/html/
fiber:
  stack_size: 1048576 # 1024 * 1024
epollvec:
  size: 5